global:
  scrape_interval: 15s # Default scrape interval

scrape_configs:
  - job_name: 'typescript-jwt-auth-app' # Job name for the application
    metrics_path: '/monitoring/metrics' # Path to scrape metrics
    static_configs:
      - targets: ['localhost:4000'] # Target for the application